config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end

  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/views/shared/_admin_dropdown.html.erb
<li>
  <%= link_to "Admin Dashboard", admin_root_path %>
</li>
<li class="divider"></li>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Overtime App Alert", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Overtime App Error", sticky: false) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false) %>
<% end %>

app/views/shared/_audit_log_tab.html.erb
<li class="<%= active?(audit_logs_path) %>">
	<%= link_to "Audit Log", audit_logs_path %>
</li>

app/views/shared/_employee_nav_items.html.erb
<li class="<%= active?(posts_path) %>">
  <%= link_to "Entries", posts_path %>
</li>
<li class="<%= active?(new_post_path) %>">
  <%= link_to "Submit Hours", new_post_path, id: 'new_post_from_nav' %>
</li>

app/views/shared/_nav.html.erb
<div class='logo'>
  <h1>Time Tracker</h1>
</div>

<% if current_user %>
  <ul class="custom-nav nav nav-tabs">
    <li class="<%= active?(root_path) %>">
      <%= link_to "", root_path, class: 'glyphicon glyphicon-home' %>
    </li>

    <%= render 'shared/employee_nav_items' if employee? %>
    <%= render 'shared/audit_log_tab' if admin? %>

    <li class="dropdown pull-right">
       <a href="#" data-toggle="dropdown" class="dropdown-toggle">Options<strong class="caret"></strong></a>
      <ul class="dropdown-menu">

        <!-- TODO -->
        <%= render 'shared/admin_dropdown' if admin? %>
        <!-- TODO -->

        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
<% end %>